FROM docker.io/library/eclipse-temurin:21-jre-alpine

ARG VALIDATOR_VERSION=1.5.0
ARG XRECHNUNG_VERSION=3.0.2
ARG XRECHNUNG_DATE=2024-06-20

WORKDIR /opt/validator

# Download KoSIT validator
ADD https://github.com/itplr-kosit/validator/releases/download/v${VALIDATOR_VERSION}/validator-${VALIDATOR_VERSION}-distribution.zip /tmp/validator.zip
RUN unzip /tmp/validator.zip -d /tmp/validator && \
    cp /tmp/validator/validationtool-${VALIDATOR_VERSION}-standalone.jar validationtool.jar && \
    rm -rf /tmp/validator /tmp/validator.zip

# Download XRechnung validation configuration
ADD https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/release-${XRECHNUNG_DATE}/validator-configuration-xrechnung_${XRECHNUNG_VERSION}_${XRECHNUNG_DATE}.zip /tmp/config.zip
RUN unzip /tmp/config.zip -d /opt/validator/config && \
    rm /tmp/config.zip

ENTRYPOINT ["java", "-jar", "validationtool.jar", \
    "-s", "config/scenarios.xml", \
    "-r", "config"]
