[person]
first_name = "Max"
last_name = "Mustermann"
birthday= "1990-01-01"
birthday_place= "Hamburg"
email = "max.mustermann@gmail.com"
phone = "+49 176 12345678"

[person.address]
street = "Musterstraße 1"
zip = "12345"
city = "Musterstadt"
country = "Deutschland"

[company]
name = "Musterfirma GmbH"
name_long = "Musterfirma GmbH & Co. KG"
email = "info@musterfirma.de"
url = "https://musterfirma.de"
phone = "+49 176 12345678"

[company.address]
street = "Musterstraße 100"
zip = "12345"
city = "Musterstadt"
country = "Deutschland"

[company.tax]
number = "12 345 6789 0"
office = "Musterstadt"

[company.bank]
iban = "DE01 2345 6789 0123 4567 89"
bic = "AAAAAAA1BBB"
bank_name = "Musterbank"

[invoice]
VAT = 0
due_days = 14

[invoice.style]
serif_font = "Palatino"
sans_font = "Helvetica"
font_size = 10
geometry = "a4paper, left=2cm, right=2cm, top=2cm, bottom=2cm"
