default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      - id: ruff-format
        name: Format Python code with Ruff
        types_or: [python, pyi]
