repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.11
    hooks:
      # Lint
      - id: ruff
        args: [--fix]
      # Format
      - id: ruff-format
