[tool.poetry]
name = "latex_templates"
version = "0.1.0"
description = "A collection of LaTeX templates."
authors = ["Felix Hoffmann <felix.emmanuel.hoffmann@gmail.com>"]
readme = "README.md"
packages = [{ include = "latex_templates" }]

[tool.poetry.dependencies]
python = "^3.12"
jinja2 = "^3.1.2"
pylatex = "^1.4.2"
fire = "^0.5.0"
loguru = "^0.7.2"

[tool.poetry.group.pydantic.dependencies]
pydantic = "^2.5.2"
email-validator = "^2.1.0.post1"
pydantic-extra-types = "^2.2.0"
phonenumbers = "^8.13.27"

[tool.poetry.group.types.dependencies]
types-pyyaml = "^6.0.12.12"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.6"
pre-commit = "^3.5.0"
mypy = "^1.7.1"

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
target-version = "py311"
line-length = 120
extend-select = [
    "B",   # flake8-bugbear
    "C",   # flake8-comprehensions
    "ERA", # flake8-eradicate/eradicate
    "I",   # isort
    "N",   # pep8-naming
    "D",   # pydocstyle
    "PL",  # Pylint
    "PTH", # flake8-use-pathlib
    "PIE", # flake8-pie
    "PGH", # pygrep
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
]
ignore = [
    "D100", # Missing docstring in public module
    "D102", # Missing docstring in public method
    "D104", # Missing docstring in public package
]

[tool.ruff.pylint]
max-args = 10

[tool.ruff.pydocstyle]
convention = "numpy"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
