settings:
  open_pdf_viewer: true
  open_mail_client: true

sender:
  address:
    name: "Musterfirma GmbH"
    street: "Musterstraße 100"
    zip: "12345"
    city: "Musterstadt"
    country: "Deutschland"
  email: "info@musterfirma.de"
  website: "https://musterfirma.de"
  phone: "+49 176 12345678"
  tax:
    number: "12 345 6789 0"
    office: "Musterstadt"
  bank:
    iban: "DE01 2345 6789 0123 4567 89"
    bic: "AAAAAAA1BBB"
    bank_name: "Musterbank"

invoice:
  VAT: 0
  due_days: 14
