name: Generate templates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-typ-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Generate invoice
        run: uv run python src/manage.py invoice --dry-run

      - name: Generate letter
        run: uv run python src/manage.py letter --dry-run

      - name: List generated files
        run: ls -l tmp

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: typ-files
          path: |
            templates/*.typ
            tmp/**/*.typ
          retention-days: 1

  # generate-pdf-files:
  #   runs-on: ubuntu-latest
  #   needs: generate-typ-files
  #   steps:
  #     - name: Download typ files
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: typ-files
  #         path: typ

  #     - uses: xu-cheng/latex-action@v3
  #       with:
  #         root_file: tex/**/*.tex

  #     - name: Upload PDF files
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: pdf-files
  #         path: |
  #           *.pdf
