name: Generate templates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-typ-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Generate invoice
        run: uv run python src/manage.py invoice --dry-run

      - name: Generate letter
        run: uv run python src/manage.py letter --dry-run

      - name: List all pdf files
        run: ls -l out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: |
            out/**/*.pdf
